language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install .
  - pip install --upgrade pytest pytest-cov python-coveralls
script: 
  - cd tests
  - py.test --cov two_cents
after_success:
  - coveralls
