#!/usr/bin/env python3

"""\
Maintain a budget that updates every day.

Usage:
    two_cents [-D] [-I]
    two_cents add-bank <name> [-u <command>] [-p <command>]
    two_cents add-budget <name> [-b <dollars>] [-a <dollars-per-time>]
    two_cents download-payments [-I]

Options:
  -D --no-download
        Don't download new transactions from the bank.  This can be a slow 
        step, so you may want to skip it if you know nothing new has happened.

  -I --no-interaction
        Don't use standard in to prompt for passwords.  If a password command 
        is found in the database, use that.  Otherwise print an error message 
        and exit.

  -u --username-cmd <command>
        When adding a new bank, use this option to specify a command that can 
        be used to get your username.  You will be prompted for one if this 
        option isn't specified.

  -p --password-cmd <command>
        When adding a new bank, use this option to specify a command that can 
        be used to get your password.  You will be prompted for one if this 
        option isn't specified.

  -b --initial-balance <dollars>
        When adding a new budget, specify how much money should start off in 
        the budget.

  -a --initial-allowance <dollars-per-time>
        When adding a new budget, specify how quickly money should accumulate 
        in that budget.
"""

# Things to do
# ============
# - Add a command to transfer money.
# - Add commands to update banks and budgets.
# - Add commands to remove banks and budgets.
# - Add a machine learning algorithm to predict assignments.
# - Add a command that just downloads payments that can be run via cron.  Then 
#   I won't ever have to wait for it to download payments when I want to check 
#   my balances.

import two_cents

def main():
    try:
        import docopt
        args = docopt.docopt(__doc__)

        with two_cents.open_db() as session:
            if args['add-bank']:
                add_bank(
                        session,
                        scraper_key=args['<name>'],
                        username_cmd=args['--username-cmd'],
                        password_cmd=args['--password-cmd'],
                )

            elif args['add-budget']:
                add_budget(
                        session,
                        name=args['<name>'],
                        initial_balance=args['--initial-balance'],
                        initial_allowance=args['--initial-allowance'],
                )

            elif args['download-payments']:
                download_payments(
                        session,
                        interactive=not args['--no-interaction'],
                )

            else:
                update_budget(
                        session,
                        download=not args['--no-download'],
                        interactive=not args['--no-interaction'],
                )

    except KeyboardInterrupt:
        print()

def add_bank(session, scraper_key, username_cmd=None, password_cmd=None):
    if two_cents.bank_exists(session, scraper_key):
        print("Bank '{}' already exists.".format(scraper_key))
        return

    if scraper_key not in two_cents.scraper_classes:
        print("Bank '{}' is not supported.".format(scraper_key))
        if len(two_cents.scraper_classes) == 1:
            print("Only '{}' is supported at present.".format(list(two_cents.scraper_classes.keys())[0]))
        else:
            print("Supported banks:", ', '.join("'{}'".format(x) for x in two_cents.scraper_classes))
        return

    if not username_cmd and not password_cmd:
        print("""\
Enter username and password commands.  You don't need to provide either 
command, but if you don't you'll have to provide the missing fields every time 
you download financial data from this bank.""")
        print()
        username_cmd = input("Username: ")
        password_cmd = input("Password: ")

    elif not username_cmd:
        print("""\
Enter a username command.  If no command is given, you'll be prompted for a 
username every time you download financial data from this bank.""")
        print()
        username_cmd = input("Username: ")

    elif not password_cmd:
        print("""\
Enter a password command.  If no command is given, you'll be prompted for a 
password every time you download financial data from this bank.""")
        print()
        password_cmd = input("Password: ")

    with two_cents.open_db() as session:
        bank = two_cents.Bank(scraper_key, username_cmd, password_cmd)
        session.add(bank)

def add_budget(session, name, initial_balance, initial_allowance):
    bank = two_cents.Budget(name, initial_balance, initial_allowance)
    session.add(bank)

def download_payments(session, interactive=True):
    two_cents.download_payments(
            session,
            get_username_prompter(interactive),
            get_username_prompter(interactive),
    )

def update_budget(session, download=True, interactive=True):
    if two_cents.get_num_budgets(session) == 0:
        print("No budgets to display.  Use 'twocents add-budget' to create some.")
        return

    if download:
        print("Downloading recent transactions...")
        download_payments(session, interactive)

    assign_payments(session)
    two_cents.update_allowances(session)
    display_budgets(session)

def assign_payments(session):
    import readline

    # Handle the payments using a simple state machine.  This architecture 
    # facilitates commands like 'skip all' and 'ignore all'.

    class ReadEvalPrintLoop:

        def __init__(self):
            self.handle = self.default_handler

        def go(self, session):
            payments = two_cents.get_unassigned_payments(session)

            if not payments:
                print("No new transactions found.")
                print()
                return

            elif len(payments) == 1:
                print("Please assign the following payment to an budget:")
                print()

            else:
                print("Please assign the following payments to budgets:")
                print()

            for payment in payments:
                self.handle(payment)

        def default_handler(self, payment):
            payment.show(indent='  ')
            print()

            while True:
                
                # Prompt the user for an assignment.

                command = input("Account: ")

                # See if the user wants to skip assigning one or more payments 
                # and come back to them later.

                if not command or command == 'skip':
                    break

                if command == 'skip all':
                    self.handle = self.null_handler
                    break

                # See if the user wants to ignore one or more payments.  These 
                # payments will be permanently excluded from the budget.

                if command == 'ignore':
                    payment.ignore()
                    break

                if command == 'ignore all':
                    payment.ignore()
                    self.handle = self.ignore_handler
                    break

                # Attempt to assign the payment to the specified budgets.  If 
                # the input can't be parsed, print an error and ask again.

                try:
                    payment.assign(command)
                    break

                except two_cents.AssignmentError as error:
                    print(error.raw_message)

            print()

        def ignore_handler(self, payment):
            payment.ignore()

        def null_handler(self, payment):
            pass

    class TabCompleter:

        def __init__(self, session):
            self.budgets = two_cents.get_budgets(session)
            self.commands = [x.name for x in self.budgets]
            self.commands += ['skip', 'ignore', 'all']
            self.commands.sort()

        def __call__(self, prefix, index):
            results = [x for x in self.commands if x.startswith(prefix)]
            try: return results[index]
            except IndexError: return None


    readline.parse_and_bind('tab: complete')
    readline.set_completer(TabCompleter(session))

    loop = ReadEvalPrintLoop()
    loop.go(session)

def display_budgets(session):
    """
    Print a line briefly summarizing each budget.
    """
    from math import log10

    budgets = two_cents.get_budgets(session)
    name_width, balance_width = 0, 0

    for budget in budgets:
        name_width = max(len(budget.name), name_width)
        balance_width = max(len(budget.pretty_balance), balance_width)

    display_template = '{{:<{}}} {{:>{}}}'.format(name_width+1, balance_width)

    for budget in two_cents.get_budgets(session):
        name = budget.name.title()
        balance = budget.pretty_balance

        if budget.recovery_time > 0:
            balance += ' ({} days)'.format(budget.recovery_time)

        print(display_template.format(name, balance))

def get_username_prompter(interactive=True):
    def username_prompter(bank, error_message):
        if error_message: print(error_message)
        return input("Username for {}: ".format(bank))
    return username_prompter

def get_password_prompter(interactive=True):
    def password_prompter(bank, error_message):
        if error_message: print(error_message)
        return getpass.getpass("Password for {}: ".format(bank))
    return password_prompter

if __name__ == '__main__':
    main()

